FROM python:3
RUN apt update && apt install -y netcat && rm -rf /var/lib/apt/lists/*
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
#COPY requirements.txt /code/
#RUN pip install --no-cache-dir -r requirements.txt
UN python


